data:
    train: Train-Test-Data/train_test_colab_combined.csv
    dev: Train-Test-Data/dev_colab.csv

audio_parameters: 
    sampling_rate: 48000
    desired_sample: 48000

melspectrogram_parameters: 
    n_mels: 128
    fmin: 20
    fmax: 24000

img_size: 224

model: 
    name: angpen-mobilenet_v2-cosface
    params:
        pretrained: True
        n_classes: 400
        embed: False

train_parameters:
    batch_size: 32
    shuffle: True
    epochs: 1000
    optimizer:
        lr: 0.01
        amsgrad: False

saved_model: saved_model/angpen_mobilenet_cosface
